import type { ProjectRequest, ProjectType } from './types';

export const projectMockList: ProjectType[] = [
  {
    projectId: 1,
    logo: '/images/example.jpg',
    title: 'EveryGSM',
    affiliation: 'The Moment',
    description: 'GSM의 모든 프로젝트를 한 눈에 확인할 수 있는 서비스입니다.',
    techStack: [{ stackName: 'Next.js' }, { stackName: 'TypeScript' }, { stackName: 'Emotion' }],
    repository: [
      { repoUrl: 'https://github.com/themoment-team/EveryGSM-client-v2', repoName: 'Service' },
    ],
    prodUrl: 'https://everygsm.com',
    liked: true,
    status: 'active',
    reason: '',
    createdAt: '2026-01-01T00:00:00Z',
  },
  {
    projectId: 2,
    logo: '/images/example.jpg',
    title: 'EveryGSM',
    affiliation: 'The Moment',
    description: 'GSM의 모든 프로젝트를 한 눈에 확인할 수 있는 서비스입니다.',
    techStack: [{ stackName: 'Next.js' }, { stackName: 'TypeScript' }, { stackName: 'Emotion' }],
    repository: [
      { repoUrl: 'https://github.com/themoment-team/EveryGSM-client-v2', repoName: 'Service' },
    ],
    prodUrl: 'https://everygsm.com',
    liked: true,
    status: 'active',
    reason: '',
    createdAt: '2026-01-01T00:00:00Z',
  },
  {
    projectId: 3,
    logo: '/images/example.jpg',
    title: 'EveryGSM',
    affiliation: 'The Moment',
    description: 'GSM의 모든 프로젝트를 한 눈에 확인할 수 있는 서비스입니다.',
    techStack: [{ stackName: 'Next.js' }, { stackName: 'TypeScript' }, { stackName: 'Emotion' }],
    repository: [
      { repoUrl: 'https://github.com/themoment-team/EveryGSM-client-v2', repoName: 'Service' },
    ],
    prodUrl: 'https://everygsm.com',
    liked: true,
    status: 'active',
    reason: '',
    createdAt: '2026-01-01T00:00:00Z',
  },
  {
    projectId: 4,
    logo: '/images/example.jpg',
    title: 'EveryGSM',
    affiliation: 'The Moment',
    description: 'GSM의 모든 프로젝트를 한 눈에 확인할 수 있는 서비스입니다.',
    techStack: [{ stackName: 'Next.js' }, { stackName: 'TypeScript' }, { stackName: 'Emotion' }],
    repository: [
      { repoUrl: 'https://github.com/themoment-team/EveryGSM-client-v2', repoName: 'Service' },
    ],
    prodUrl: 'https://everygsm.com',
    liked: true,
    status: 'active',
    reason: '',
    createdAt: '2026-01-01T00:00:00Z',
  },
  {
    projectId: 5,
    logo: '/images/example.jpg',
    title: 'EveryGSM',
    affiliation: 'The Moment',
    description: 'GSM의 모든 프로젝트를 한 눈에 확인할 수 있는 서비스입니다.',
    techStack: [{ stackName: 'Next.js' }, { stackName: 'TypeScript' }, { stackName: 'Emotion' }],
    repository: [
      { repoUrl: 'https://github.com/themoment-team/EveryGSM-client-v2', repoName: 'Service' },
    ],
    prodUrl: 'https://everygsm.com',
    liked: true,
    status: 'active',
    reason: '',
    createdAt: '2026-01-01T00:00:00Z',
  },
  {
    projectId: 6,
    logo: '/images/example.jpg',
    title: 'EveryGSM',
    affiliation: 'The Moment',
    description: 'GSM의 모든 프로젝트를 한 눈에 확인할 수 있는 서비스입니다.',
    techStack: [{ stackName: 'Next.js' }, { stackName: 'TypeScript' }, { stackName: 'Emotion' }],
    repository: [
      { repoUrl: 'https://github.com/themoment-team/EveryGSM-client-v2', repoName: 'Service' },
    ],
    prodUrl: 'https://everygsm.com',
    liked: true,
    status: 'active',
    reason: '',
    createdAt: '2026-01-01T00:00:00Z',
  },
];

export const projectRequestMockList: ProjectRequest[] = [
  {
    id: 1,
    imageSrc: '/images/example.jpg',
    projectName: 'EveryGSM v2',
    teamName: 'The Moment',
    date: '2026-01-27',
    requestStatus: '확인 중',
  },
  {
    id: 2,
    imageSrc: '/images/example.jpg',
    projectName: 'Old Project',
    teamName: 'Old Team',
    date: '2025-12-25',
    requestStatus: '거절',
  },
  {
    id: 3,
    imageSrc: '/images/example.jpg',
    projectName: 'New Idea',
    teamName: 'Dream Team',
    date: '2026-01-20',
    requestStatus: '승인',
  },
];
